In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[2,3,4]])

In [8]:
array

array([[1, 2, 3],
       [2, 3, 4]])

In [4]:
print(array.ndim)

2


In [6]:
print(array.shape)

(2, 3)


In [7]:
array.size

6

In [12]:
a = np.array([2,23,4],dtype=np.float)
a.dtype

dtype('float64')

In [13]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
c = np.ones((3,4),dtype=np.float)
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
d = np.arange(10,20,2)
d

array([10, 12, 14, 16, 18])

In [17]:
e = np.arange(12).reshape((3,4))
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
f = np.linspace(1,10,20)
f

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [19]:
a = np.array([10,20,30,40])
b = np.arange(4)

In [20]:
c = a+b
c

array([10, 21, 32, 43])

In [21]:
c = b**2
c

array([0, 1, 4, 9])

In [22]:
c = 10 * np.sin(a)
c

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [23]:
print(b<3)

[ True  True  True False]


In [25]:
#逐个相乘
c = a*b
#矩阵乘法
d = np.dot(a,b)
d1 = a.dot(b)
print('c',c)
print('d',d)
print('d1',d1)

c [  0  20  60 120]
d 200
d1 200


In [26]:
#从0到1随机生成数字
a = np.random.random((2,4))
a

array([[0.54502408, 0.82492353, 0.00512872, 0.1605905 ],
       [0.02694569, 0.079952  , 0.61856607, 0.86348113]])

In [28]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))

3.124611710984382
0.0051287158685696665
0.8634811330779986
0.39057646387304773


In [30]:
print(np.sum(a,axis=0))#colomn
print(np.sum(a,axis=1))#raw

[0.57196976 0.90487553 0.62369479 1.02407163]
[1.53566682 1.58894489]


In [31]:
A = np.arange(2,14).reshape((3,4))
A

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [32]:
np.argmin(A)

0

In [33]:
np.mean(A)

7.5

In [34]:
#累加
np.cumsum(A)

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90])

In [35]:
#累差，每两个数之间的差
np.diff(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
#找出非0的数
np.nonzero(A)
#第一个是非0元素的行数，第二个是列数

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [37]:
#像列表一样，排序
#逐行排序
np.sort(A)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [39]:
#矩阵转置
print(np.transpose(A))
print(A.T)
print((A.T).dot(A))

[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]


In [40]:
#clip 功能
print(A)
print(np.clip(A,5,9))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [41]:
##索引##

In [43]:
A = np.arange(3,15)
A

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
type(A)

numpy.ndarray

In [44]:
A[3]

6

In [47]:
A = np.arange(3,15).reshape((3,4))
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [46]:
A[2]

array([11, 12, 13, 14])

In [48]:
A[1][1]

8

In [49]:
A[1,1]

8

In [53]:
print(A[2,:])
print(A[2,1:2])

[11 12 13 14]
[12]


In [54]:
#显示行
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [55]:
#显示列
for col in A.T:
    print(col)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [58]:
#显示每个元素
print(A.flat)   #flat 是个迭代器,返回object/function
print(A.flatten()) #flatten()返回被改变的array
for item in A.flatten(): #A.flat也行
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [59]:
##numpy 的array合并##

In [63]:
A = np.array([1,1,1])
B= np.array([2,2,2])
C = np.vstack((A,B))  #vertical stack
print(A.shape,C.shape)
print(C)

(3,) (2, 3)
[[1 1 1]
 [2 2 2]]


In [65]:
D = np.hstack((A,B)) #horizontal stack 左右合并
print(D)
print(D.shape)

[1 1 1 2 2 2]
(6,)


In [70]:
#实现把横向的array变为纵向的数列
print(A.T)
#在行上加一个维度
E = A[np.newaxis,:]
print(E.shape, E)
#列上加维度
F = A[:,np.newaxis]
print(F.shape, F)

[1 1 1]
(1, 3) [[1 1 1]]
(3, 1) [[1]
 [1]
 [1]]


In [73]:
A = np.array([1,1,1])[:,np.newaxis]
B= np.array([2,2,2])[:,np.newaxis]
C = np.vstack((A,B))
D = np.hstack((A,B))
print('A',A)
print('B',B)
print('C',C)
print('D',D)

A [[1]
 [1]
 [1]]
B [[2]
 [2]
 [2]]
C [[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
D [[1 2]
 [1 2]
 [1 2]]


In [76]:
#多个array的合并
E1 = np.concatenate((A,B,B,A),axis=0)#axis=0,列
E2 = np.concatenate((A,B,B,A),axis=1)
print('E1',E1)
print('E2',E2)

E1 [[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
E2 [[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [77]:
##分割##

In [78]:
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [79]:
#横向分割split
B = np.split(A,2,axis=1) #第二个参数表示分割成几块，axis表示方向
print(B)


[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [86]:
C = np.split(A,3,axis=0)#不能进行不等的分割：每列3个元素，不能分为2块
#print(np.split(A,3,axis=1)) #error
print(C)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [87]:
##进行不等量的分割：：np,array_split()
D = np.array_split(A,3,axis=1)
print(D)

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [88]:
#类似于np.nstack, np.vstack
E = np.vsplit(A,3)
F= np.hsplit(A,2)
print(E)
print(F)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [89]:
##copy, deep copy##

In [90]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [91]:
b =a 
c = a 
d = b
print(b is a)

True


In [94]:
a[0] = 11
print(a)
print(b)
print(c)
print(d)

[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]


In [96]:
d[1:3] = [22,33]
print(a)
print(b)
print(c)
print(d)

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


In [97]:
#deep copy
b = a.copy()
b

array([11, 22, 33,  3])

In [98]:
a[3] = 44
print(a)
print(b)
print(c)
print(d)

[11 22 33 44]
[11 22 33  3]
[11 22 33 44]
[11 22 33 44]
